spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wrappedfy
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

spotify:
  client-id: local
  client-secret: local
  redirect-uri: http://localhost:8080/callback